dataset_path: "dataset/OcamLib"

# possible models : EUCM, DS, UCM, KB, OcamLib
input_model: "KB"
output_model: "EUCM"

image_name: "image.jpg"
show_image: false

sample_point: 500

result_path: "result"
save_result: false

display_optimization_progress: false
evaluation: true
