dataset_path: "dataset/kalibr"

# possible models : EUCM, DS, UCM, KB, OcamCalib
input_model: "KB"
output_model: "OcamCalib"

image_name: "image.png"
show_image: true

sample_point: 500

result_path: "result"
save_result: false

display_optimization_progress: false
evaluation: true
